import type { Metadata } from "next";
import { Inter_Tight } from 'next/font/google'
import "./globals.css";
import Header from "@/components/Header";

const interTight = Inter_Tight({ 
  subsets: ['latin'], 
  weight: ['400', '500', '700'], // Exemplo de pesos da fonte
  variable: '--font-inter-tight' 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.variable} ${interTight.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
